channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - beautifulsoup4
  - ca-certificates
  - clang=14
  - clang-14
  - ipython
  - kiwisolver
  - matplotlib
  - notebook
  - numpy=1.24.3
  - pandas=1.5.3
  - pip
  - python=3.8.10
  - qt=5.15.9
  - requests
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - setuptools
  - tqdm
  - pip:
      - annoy
      - filelock
      - gym<=0.22.0
      - torch
      - h5py
      - mdptoolbox-hiive
      - opencv-python
      - pfrl
      - pillow
      - protobuf
      - pydot
      - pyglet
      - sumolib
      - traci
      - xxhash
